[package]
name = "actix-scaffolding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.1"
actix-cors = "0.7.0"
actix-web = "4.4.1"
dotenv = "0.15.0"
sailfish = "0.8.3"
